spring.application.name=url-shortner
spring.config.import=optional:file:.env[.properties]
spring.data.redis.url=${UPSTASH_REDIS_URL}
spring.data.redis.timeout=500ms

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

app.base-url=${APP_BASE_URL}

rate-limit.create-url.max-requests=100
rate-limit.create-url.window-seconds=60